[package]
name = "four-bar"
version = "0.1.0"
authors = ["KmolYuan <pyslvs@gmail.com>"]
edition = "2018"
description = "Four🍀bar is a simulator, a synthesizing tool for four-bar linkage mechanism."

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = "0.13"
serde = { version = "1", features = ["derive"], optional = true }

[features]
default = []
http = ["eframe/http"]
persistence = ["eframe/persistence", "serde"]

[profile.release]
opt-level = 2 # fast and small wasm
