[package]
name = "four-bar-ui"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Four🍀bar GUI is a simulator, a synthesizing tool for four-bar linkages."
readme = "../README.md"
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "four-bar"
path = "src/main.rs"

[features]
# Turn of default in WASM
default = ["native"]
native = ["four-bar/rayon", "four-bar/mh-clap"]

[dependencies]
serde = { version = "1", features = ["derive"] }
ron = "0.8"

[dependencies.four-bar]
version = "4"
path = "../four-bar"
features = ["csv", "codebook", "plot"]

[dependencies.eframe]
version = "0.21"
default-features = false
features = ["persistence", "glow", "dark-light"]

[dependencies.image]
version = "0.24"
default-features = false
features = ["ico", "jpeg"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# native here!
indicatif = { version = "0.17", features = ["improved_unicode"] }
clap = { version = "4", features = ["derive"] }
rfd = "0.11"
wild = "2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# wasm here!
instant = { version = "0.1", features = ["stdweb"] }
console_error_panic_hook = "0.1"
tracing-wasm = "0.2"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[target.'cfg(windows)'.dependencies]
# windows here!
winapi = { version = "0.3", features = ["wincon", "winuser"] }

[target.'cfg(windows)'.build-dependencies]
image = "0.24"
winres = "0.1"
