[package]
name = "four-bar-ui"
version = "0.3.0"
authors = ["KmolYuan <pyslvs@gmail.com>"]
edition = "2021"
description = "Four🍀bar GUI is a simulator, a synthesizing tool for four-bar linkage mechanism."
license = "AGPL-3.0-or-later"
readme = "../README.md"
repository = "https://github.com/KmolYuan/four-bar-rs"
keywords = ["mechanism", "simulation", "optimization"]
categories = ["algorithms"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
four-bar = { version = "0.3", path = "../four-bar", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
eframe = { version = "0.15", features = ["persistence"] }
hmac-sha512 = "1"
ron = "0.7"
csv = "1.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# native here!
clap = "2.34"
temp-dir = "0.1"
zip = "0.5"
actix-web = "4.0.0-beta"
actix-identity = "0.4.0-beta"
actix-files = "0.6.0-beta"
rfd = "0.6"
atomic = "0.5"
ureq = { version = "2", features = ["cookies"] }
cookie_store = "0.15"
time = "0.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# wasm here!
wasm-bindgen = "0.2"
js-sys = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.build-dependencies]
image = "0.23"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
