[package]
name = "four-bar-ui"
version = "0.1.0"
authors = ["KmolYuan <pyslvs@gmail.com>"]
edition = "2018"
description = "Four🍀bar is a simulator, a synthesizing tool for four-bar linkage mechanism."

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ['persistence']
http = ["eframe/http"]
persistence = ["eframe/persistence", "serde", "four-bar/serde"]

[dependencies]
four-bar = { path = "../four-bar" }
eframe = "0.14"
serde = { version = "1", features = ["derive"], optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# use to load the icon
image = "0.23"
four-bar = { path = "../four-bar", features = ["synthesis"] }
csv = "1.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
