[package]
name = "four-bar-ui"
version = "0.2.0"
authors = ["KmolYuan <pyslvs@gmail.com>"]
edition = "2021"
description = "Four🍀bar is a simulator, a synthesizing tool for four-bar linkage mechanism."
license-file = "../LICENSE"
readme = "../README.md"
repository = "https://github.com/KmolYuan/four-bar-rs"
keywords = ["mechanism", "simulation", "optimization"]
categories = ["algorithms"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
four-bar = { path = "../four-bar", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
eframe = { version = "0.15", features = ["persistence"] }
async-std = "1.9"
ron = "0.7"
# use "ehttp" for client side service

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
csv = "1.1"
rfd = "0.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"
js-sys = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.build-dependencies]
image = "0.23"
