[package]
name = "four-bar-ui"
version = "0.3.0"
authors = ["KmolYuan <pyslvs@gmail.com>"]
edition = "2021"
description = "Four🍀bar GUI is a simulator, a synthesizing tool for four-bar linkage mechanism."
license-file = "../LICENSE"
readme = "../README.md"
repository = "https://github.com/KmolYuan/four-bar-rs"
keywords = ["mechanism", "simulation", "optimization"]
categories = ["algorithms"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
four-bar = { version = "0.3", path = "../four-bar", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
eframe = { version = "0.15", features = ["persistence"] }
ron = "0.7"
csv = "1.1"
# use "ehttp" for client side service

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# native here!
clap = "2.34"
temp-dir = "0.1"
zip = "0.5"
reqwest = "0.11"
actix-web = { version = "4.0.0-beta.13", features = ["openssl"] }
actix-files = "0.6.0-beta"
openssl = "0.10"
rcgen = "0.8"
rfd = "0.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# wasm here!
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"
js-sys = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.build-dependencies]
image = "0.23"
