[package]
name = "four-bar-ui"
version = "2.0.0"
authors = ["KmolYuan <pyslvs@gmail.com>"]
edition = "2021"
description = "Four🍀bar GUI is a simulator, a synthesizing tool for four-bar linkage mechanism."
license = "AGPL-3.0-or-later"
readme = "../README.md"
repository = "https://github.com/KmolYuan/four-bar-rs"
keywords = ["mechanism", "simulation", "optimization"]
categories = ["algorithms"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = { version = "0.18", default-features = false, features = ["persistence", "dark-light"] }
four-bar = { version = "2", path = "../four-bar", features = ["serde", "plot"] }
serde = { version = "1", features = ["derive"] }
ron = "0.7"
csv = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# native here!
four-bar = { version = "2", path = "../four-bar", features = ["rayon"] }
clap = { version = "3", features = ["derive"] }
image = "0.24"
rfd = "0.10"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# wasm here!
instant = { version = "0.1", features = ["stdweb"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"

[target.'cfg(windows)'.dependencies]
# windows here!
winapi = { version = "0.3", features = ["wincon", "winuser"] }

[target.'cfg(windows)'.build-dependencies]
image = "0.24"
winres = "0.1"
