[package]
name = "four-bar-ui"
version = "1.0.0"
authors = ["KmolYuan <pyslvs@gmail.com>"]
edition = "2021"
description = "Four🍀bar GUI is a simulator, a synthesizing tool for four-bar linkage mechanism."
license = "AGPL-3.0-or-later"
readme = "../README.md"
repository = "https://github.com/KmolYuan/four-bar-rs"
keywords = ["mechanism", "simulation", "optimization"]
categories = ["algorithms"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
four-bar = { version = "1", path = "../four-bar", features = ["serde"] }
eframe = { version = "0.18", features = ["persistence"] }
serde = { version = "1", features = ["derive"] }
hmac-sha512 = "1"
ron = "0.7"
csv = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# native here!
clap = { version = "3", features = ["derive"] }
ureq = { version = "2", features = ["cookies"] }
actix-web = "4"
actix-identity = "0.4"
actix-files = "0.6"
webbrowser = "0.7"
temp-dir = "0.1"
zip = "0.6"
rfd = "0.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
# wasm here!
wasm-bindgen = "0.2"

[target.'cfg(windows)'.dependencies]
# windows here!
winapi = { version = "0.3", features = ["wincon", "winuser"] }

[target.'cfg(not(target_arch = "wasm32"))'.build-dependencies]
image = "0.24"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
