name: Github Deploy
on:
  push:
    tags: [ v* ]
jobs:
  cargo-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo login ${{ secrets.CRATE_IO }}
          cargo publish -p four-bar
  gh-pages-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          sudo apt update
          sudo apt install -y binaryen
          ./setup_web.sh
          ./build_web.sh
      - name: Pack WASM
        uses: papeloto/action-zip@v1
        with:
          files: docs/
          dest: four-bar-wasm-unknown.zip
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        with:
          files: four-bar-wasm-unknown.zip
  gh-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: four-bar-ui
            asset_name: four-bar-linux-amd64
          - os: macOS-latest
            artifact_name: four-bar-ui
            asset_name: four-bar-macos-amd64
          - os: windows-latest
            artifact_name: four-bar-ui.exe
            asset_name: four-bar-windows-amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update
          sudo apt install -y libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libgtk-3-dev
      - shell: bash
        run: cargo build --all-features --release
      - name: Pack binaries
        uses: papeloto/action-zip@v1
        with:
          files: target/release/${{ matrix.artifact_name }}
          dest: ${{ matrix.asset_name }}.zip
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        with:
          files: ${{ matrix.asset_name }}.zip
