[package]
name = "four-bar"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Four🍀bar library provides simulation and synthesis function for four-bar linkages."
readme = "README.md"
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = []
plot = ["plotters"]
serde = ["dep:serde", "metaheuristics-nature/serde"]
mh-clap = ["metaheuristics-nature/clap"]
rayon = ["metaheuristics-nature/rayon"]
codebook = ["ndarray-npy"]

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }
ndarray-npy = { version = "0.8", optional = true }
metaheuristics-nature = "8"
efd = "0.25"

[dependencies.plotters]
version = "0.3"
default-features = false
features = ["svg_backend", "all_series", "all_elements"]
optional = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]
