[package]
name = "four-bar"
version = "0.5.1"
authors = ["KmolYuan <pyslvs@gmail.com>"]
edition = "2021"
description = "Four🍀bar library provides simulation and synthesis function for four-bar linkage mechanism."
license = "AGPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/KmolYuan/four-bar-rs"
keywords = ["mechanism", "simulation", "optimization"]
categories = ["algorithms"]

[features]
plot = ["plotly"]
plot_export = ["plot", "plotly/kaleido"]

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }
plotly = { version = "0.7", optional = true }
metaheuristics-nature = { version = "0.23", features = ["parallel"] }
efd = "0.11"
rayon = "1.5"

[dev-dependencies]
indicatif = "0.16"
ron = "0.7"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]
