[package]
name = "four-bar"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Four🍀bar library provides simulation and synthesis function for four-bar linkages."
readme = "README.md"
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = []
plot = ["plotters", "plotters-backend", "fmtastic"]
serde = ["dep:serde", "metaheuristics-nature/serde"]
clap = ["dep:clap", "metaheuristics-nature/clap"]
rayon = ["metaheuristics-nature/rayon"]
atlas = ["ndarray-npy"]
csv = ["dep:csv", "serde"]

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }
plotters-backend = { version = "0.3", optional = true }
ndarray-npy = { version = "0.8", optional = true }
fmtastic = { version = "0.1", optional = true }
clap = { version = "4", optional = true }
csv = { version = "1", optional = true }
metaheuristics-nature = "9.2.2"
efd = "5"

[dependencies.plotters]
version = "0.3"
default-features = false
features = ["svg_backend", "all_series", "all_elements", "full_palette"]
optional = true

[dev-dependencies]
approx = "0.5"

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]
