[package]
name = "four-bar"
version = "0.1.0"
authors = ["KmolYuan <pyslvs@gmail.com>"]
edition = "2018"
description = "Four🍀bar is a simulator, a synthesizing tool for four-bar linkage mechanism."

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }
ndarray = "0.15"
metaheuristics-nature = { version = "0.14", features = ["parallel"] }
efd = "0.5.3"
plotters = "0.3"

[dev-dependencies]
indicatif = "0.16"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]
